# enable debug
debug: true

# server config
server:
    port: :80
    token:

# db config
db:
    host: 127.0.0.1
    port: 3306
    name: enturn
    username: root
    password: root

# redis config
redis:
    host: 127.0.0.1
    port: 6379
    db: 0
    password:
